### ISSUE TITLE
Fresh install fails

### ISSUE THREAD

**Issue by mrmarcsmith** [jx3-gitops-repositories/jx3-terraform-eks#22]
I followed the readme with fresh repos and the installation failed. I'm going to include details about everything I did in hopes we can fix this template. I really want jx3 to take off but the adoption of jx3 is totally dependent on these templates working out of the box. I'm going to put in some work and make a PR to fix the easy things I found but I need help with the secrets population issue at the end.

1. used the template links to create new repos 
2. added the my bot account as a collaborator
3. made this single commit (2 file changes) to the infrastructure repo

<img width="1222" alt="Screen Shot 2021-09-16 at 10 53 09 PM" src="https://user-images.githubusercontent.com/5037688/133731554-4871be7e-555e-4bbd-a03b-a94d9ae992c1.png">

<img width="1219" alt="Screen Shot 2021-09-16 at 10 53 23 PM" src="https://user-images.githubusercontent.com/5037688/133731542-88c8dc2a-5288-4d8c-9ce3-1adeb1094dc2.png">
4. exported the following env vars

```
export TF_VAR_jx_bot_token=<REDACTED>
export AWS_PROFILE=dev_root
```
my ~/.aws/credentials file looks like this:
```
[default]
aws_access_key_id = <REDACTED>
aws_secret_access_key = <REDACTED>

[dev_root]
role_arn = arn:aws:iam::<REDACTED>:role/OrganizationAccountAccessRole
source_profile = default
```

6. ran `terraform init` and received this error
<img width="805" alt="Screen Shot 2021-09-16 at 11 09 51 PM" src="https://user-images.githubusercontent.com/5037688/133733194-0f8dc9f1-2f7c-4a11-9d73-a0afa088a0cb.png">

7. removed the ref to fix
<img width="1223" alt="Screen Shot 2021-09-16 at 11 11 20 PM" src="https://user-images.githubusercontent.com/5037688/133733283-5d89db99-c3ba-4de7-a12e-bc3201e654a0.png">

8. re-ran `terraform init` and received this error
<img width="1224" alt="Screen Shot 2021-09-16 at 11 21 05 PM" src="https://user-images.githubusercontent.com/5037688/133734285-bd590395-2a0f-4efb-bab7-a0e37dd15668.png">

9. ran `terraform init -upgrade` to fix

10. ran the code and it passed:
```
terraform init
terraform plan
terraform apply
```
<img width="763" alt="Screen Shot 2021-09-16 at 11 49 15 PM" src="https://user-images.githubusercontent.com/5037688/133737438-3225b824-82f0-44a0-b73c-ef2a61c6c505.png">
 
11. I tailed the logs with `jx admin logs` and saw this error at the end. Random thought: Is there some additional step not outlined in the README I need to perform to populate those secrets manually or should they be populated automatically?
```

saved docs/releases.yaml
saved docs/README.md
jx gitops scheduler
jx gitops hash --pod-spec --kind Deployment -s config-root/namespaces/jx/lighthouse-config/config-cm.yaml -s config-root/namespaces/jx/lighthouse-config/plugins-cm.yaml -d config-root/namespaces/jx/lighthouse
jx gitops label --dir config-root/cluster                   gitops.jenkins-x.io/pipeline=cluster
jx gitops label --dir config-root/customresourcedefinitions gitops.jenkins-x.io/pipeline=customresourcedefinitions
jx gitops label --dir config-root/namespaces                gitops.jenkins-x.io/pipeline=namespaces
jx gitops annotate --dir config-root --selector app=pusher-wave kapp.k14s.io/change-group=apps.jenkins-x.io/pusher-wave
jx gitops annotate --dir config-root --selector app.kubernetes.io/name=ingress-nginx kapp.k14s.io/change-group=apps.jenkins-x.io/ingress-nginx
jx gitops label --dir config-root/cluster --kind=Namespace team=jx
jx gitops annotate --dir  config-root/namespaces --kind Deployment --selector app=pusher-wave --invert-selector wave.pusher.com/update-on-config-change=true
jx gitops git setup
found git user.name qube-bot from requirements
found git user.email  from requirements
setup git user  email jenkins-x@googlegroups.com
generated Git credentials file: /workspace/xdg_config/git/credentials with username: qube-bot email: 
git add --all
git commit -m "chore: regenerated" -m "/pipeline cancel"
[main dcd6737] chore: regenerated
 17 files changed, 18 insertions(+), 18 deletions(-)
make[1]: Leaving directory '/workspace/source'
make regen-phase-3
make[1]: Entering directory '/workspace/source'
Already up to date.
To https://github.com/mrmarcsmith/jenkins-x-dev-cluster.git
   ba3cbc2..dcd6737  main -> main
VAULT_ADDR=https://vault.jx-vault:8200 VAULT_NAMESPACE=jx-vault jx secret populate --secret-namespace jx-vault
waiting for vault pod vault-0 in namespace jx-vault to be ready...
pod vault-0 in namespace jx-vault is ready
verifying we have vault installed
about to run: /root/.jx/plugins/bin/vault-1.6.1 version
Vault v1.6.1 (6d2db3f033e02e70202bef9ec896360062b88b03)
verifying we can connect to vault...
about to run: /root/.jx/plugins/bin/vault-1.6.1 kv list secret
Keys
----
accounts/
dockerrepo
mysql
vault is setup correctly!

managed to verify we can connect to vault
VAULT_ADDR=https://vault.jx-vault:8200 jx secret wait -n jx
waiting for the mandatory Secrets to be populated from ExternalSecrets...
jenkins-x-chartmuseum: key secret/data/jx/adminUser missing properties: password, username
jx-basic-auth-user-password: key secret/data/jx/basic/auth/user missing properties: password, key secret/data/jx/basic/auth/user/password missing properties: username
lighthouse-hmac-token: key secret/data/lighthouse/hmac missing properties: token
lighthouse-oauth-token: key secret/data/lighthouse/oauth missing properties: token
nexus: key secret/data/nexus missing properties: password
tekton-container-registry-auth: key secret/data/tekton/container/registry/auth missing properties: .dockerconfigjson
tekton-git: key secret/data/jx/pipelineUser missing properties: token, username
```

12. ran `jx ui` and gathered these relevant error messages
<img width="1564" alt="Screen Shot 2021-09-16 at 11 55 59 PM" src="https://user-images.githubusercontent.com/5037688/133738279-70b97a8e-f1f1-48fe-aadf-d32f500ff4de.png">
<img width="1559" alt="Screen Shot 2021-09-16 at 11 57 08 PM" src="https://user-images.githubusercontent.com/5037688/133738429-d17a6c19-52e9-4b96-8a68-4c313852d26f.png">

13. ran `kubectl get pods --all-namespaces` and noticed these failed containers
<img width="915" alt="Screen Shot 2021-09-16 at 11 58 42 PM" src="https://user-images.githubusercontent.com/5037688/133738627-d5eb4a20-f98f-4fbc-8506-3ca8ac5c4c21.png">

14. ran `kubectl logs jx-preview-gc-jobs-27197690-6kjcs` output only this:
```
WARNING: could not default pipeline user/email from requirements as file does not exist: jx-requirements.yml
error: creating git credentials: failed to load the boot secret: failed to find boot secret: failed to find secret tekton-git in namespace jx or jx-git-operator: secrets "tekton-git" not found
```

15. ran `kubectl describe pod jenkins-x-chartmuseum-79c9b8dcd9-vv9sx -n jx`
```
Events:
  Type     Reason                  Age                   From                                 Message
  ----     ------                  ----                  ----                                 -------
  Normal   Scheduled               19m                   default-scheduler                    Successfully assigned jx/jenkins-x-chartmuseum-79c9b8dcd9-vv9sx to ip-10-0-1-246.ec2.internal
  Normal   SuccessfulAttachVolume  19m                   attachdetach-controller              AttachVolume.Attach succeeded for volume "pvc-27fed11e-906d-4e9e-9948-d38a7ec760e5"
  Normal   Pulling                 19m                   kubelet, ip-10-0-1-246.ec2.internal  Pulling image "chartmuseum/chartmuseum:v0.12.0"
  Normal   Pulled                  19m                   kubelet, ip-10-0-1-246.ec2.internal  Successfully pulled image "chartmuseum/chartmuseum:v0.12.0" in 2.599439293s
  Warning  Failed                  17m (x12 over 19m)    kubelet, ip-10-0-1-246.ec2.internal  Error: secret "jenkins-x-chartmuseum" not found
  Normal   Pulled                  4m24s (x70 over 19m)  kubelet, ip-10-0-1-246.ec2.internal  Container image "chartmuseum/chartmuseum:v0.12.0" already present on machine
```

16. ran `kubectl describe pod lighthouse-foghorn-86b84cb46c-dkrzm -n jx`
```
Events:
  Type     Reason     Age                 From                                 Message
  ----     ------     ----                ----                                 -------
  Normal   Scheduled  21m                 default-scheduler                    Successfully assigned jx/lighthouse-foghorn-86b84cb46c-dkrzm to ip-10-0-3-201.ec2.internal
  Normal   Pulling    21m                 kubelet, ip-10-0-3-201.ec2.internal  Pulling image "ghcr.io/jenkins-x/lighthouse-foghorn:1.1.51"
  Normal   Pulled     21m                 kubelet, ip-10-0-3-201.ec2.internal  Successfully pulled image "ghcr.io/jenkins-x/lighthouse-foghorn:1.1.51" in 3.272873027s
  Warning  Failed     19m (x12 over 21m)  kubelet, ip-10-0-3-201.ec2.internal  Error: secret "lighthouse-oauth-token" not found
  Normal   Pulled     84s (x94 over 21m)  kubelet, ip-10-0-3-201.ec2.internal  Container image "ghcr.io/jenkins-x/lighthouse-foghorn:1.1.51" already present on machine
```

**Comment by ankitm123** [comment]
Can you paste the full output of  `jx admin log`? May be create a gist. Things (Bad ones) happened much before the errors that you posted.

**Comment by mrmarcsmith** [comment]
Yes, I will paste the full jx admin log soon

**Comment by mrmarcsmith** [comment]
here is the js admin log output [jx_admin_log.txt](https://github.com/jx3-gitops-repositories/jx3-terraform-eks/files/7188255/jx_admin_log.txt)

Yes, there is a jx-requirements.yml in my jx-eks-vault repo I will paste the redacted version here.

please let me know what else I can do to help.

**Comment by mrmarcsmith** [comment]
```
apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: tf-jx-sweeping-insect
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    project: "7777777777"
    provider: eks
    region: us-east-1
    registry: 7777777777.dkr.ecr.us-east-1.amazonaws.com
  environments:
  - key: dev
    owner: mrmarcsmith
    repository: jenkins-x-dev-cluster
  - key: staging
  - key: production
  ingress:
    domain: 77.77.77.77.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: qube-bot
  repository: nexus
  secretStorage: vault
  storage:
  - name: logs
    url: s3://logs-tf-jx-sweeping-insect-20210917777777777777777
  - name: reports
    url: s3://reports-tf-jx-sweeping-insect-20210917777777777777777
  - name: repository
    url: s3://repository-tf-jx-sweeping-insect-202109177777777777777777
  terraform: true
  vault:
    aws:
      dynamoDBRegion: us-east-1
      dynamoDBTable: vault-unseal-tf-jx-sweeping-insect-777777
      kmsKeyId: 77777777-7777-7777-7777-777777777777
      kmsRegion: us-east-1
      s3Bucket: vault-unseal-tf-jx-sweeping-insect-202109177777777777777777
      s3Region: us-east-1
  webhook: lighthouse
```

I only changed numbers to 7's everything else is unchanged
